echo 'oh!'
Plug 'scrooloose/nerdcommenter'
Plug 'vim-scripts/SQLUtilities'
Plug 'rhysd/vim-crystal'
Plug 'kwstannard/align'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-vinegar'
Plug 'flazz/vim-colorschemes'
Plug 'vim-ruby/vim-ruby'
" Plug 'bruno-/vim-ruby-fold'
Plug 'rust-lang/rust.vim'
Plug 'cespare/vim-toml'
Plug 'editorconfig/editorconfig-vim'
Plug 'junegunn/fzf'
Plug 'derekwyatt/vim-scala'
Plug 'vim-syntastic/syntastic'
Plug 'JamshedVesuna/vim-markdown-preview'
Plug 'kana/vim-arpeggio'
