#!/usr/bin/env ruby

if ENV['SKIP_JIRA']
  exit 0
end

story=`git story`.strip

tmp=File.read(ARGV[0])
  .gsub(/\n+### Jira.*/, "").tap{ |m| puts m }
	.+ "\n### Jira [#{story}](#{ENV["JIRA_STORY_URL"]}#{story})\n"
File.write(ARGV[0], tmp)
