alias notes="vim \$(mktemp -d -t notes)/notes.txt"
alias standup="vim \$HOME/Google\ Drive/standup/\$(date "+%m-%d-%y").txt"
alias 1on1="vim \$HOME/Google\ Drive/1on1/\$(date "+%m-%d-%y").txt"
alias line_xargs="tr '\n' '\0' | xargs -0 "
alias jit="de git"
