source ~/scripts/init.bash
alias powrestart=`touch ~/.pow/restart.txt`

export PATH=/Users/kstannard/scripts/bin:$PATH
export PATH=/usr/local/bin:$PATH

# eval $(ruby ~/Sites/scripts/dev_machine/lib/generate_gem_dir_env_functions.rb)
# set_all_gem_dirs

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
#export PATH="$HOME/.rbenv/bin:$PATH"
#eval "$(rbenv init -)"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

eval "$(rbenv init -)"

alias redisstart='sudo launchctl start io.redis.redis-server'
alias redisstop='sudo launchctl stop io.redis.redis-server'
