#! /env/bin/ruby

require_relative '../../../utility/executor'
require 'fileutils'

class Setuper
  def call
    link_script_dir
    link_bashrc
  end

  def link_script_dir
    if !Dir.exist? "#{Dir.home}/scripts"
      FileUtils.ln_s '/Volumes/shared/scripts', "#{Dir.home}/scripts"
    end
  end

  def link_bashrc
    FileUtils.ln_s ""#{Dir.home}/.bashrc"
  end

  def ex(*args)
    execution = Executor.new(self, *args)
    executions << execution
    execution.call
  end
end

Setuper.new.call
