source ~/scripts/init.bash

source $HOME/.work_env_variables
export NVM_DIR="/Users/stannard/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"
export PGDATA=/usr/local/var/postgres/
export OCI_DIR=/opt/oracle/instantclient_12_2

if [[ -z "$TMUX" ]]; then
  if tmux has-session 2>/dev/null; then
    exec tmux attach
  else
    exec tmux
  fi
else
  echo 'creating windows'
  ruby -e "
    ((%x[tmux list-windows | wc -l].to_i)...25).each do
      %x[tmux new-window]
    end
  "

  #exec tmux set status off
fi
