if [[ -z "$TMUX" ]]; then
  if tmux has-session 2>/dev/null; then
    exec tmux attach
  else
    exec tmux
  fi
else
  echo 'creating windows'
  ruby -e "
    ((%x[tmux list-windows | wc -l].to_i)...25).each do |i|
      %x[tmux new-window -d -t #{i} 2>/dev/null]
    end
  "

  source ~/scripts/init.bash

  #exec tmux set status off
fi
