# ~/.bash_profile: executed by bash(1) for login shells.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/login.defs
#umask 022

# include .bashrc if it exists
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi
if [ -e /home/kwstannard/.nix-profile/etc/profile.d/nix.sh ]; then . /home/kwstannard/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

export PATH=./bin:$PATH
