# User specific aliases and functions
source ~/scripts/init.bash

export PGDATA=/var/lib/pgsql/data
export PATH="$HOME/bin:$PATH"

if [ -f ~/.private_bashrc ]; then
  source ~/.private_bashrc.bash
fi

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

shopt -s checkwinsize

export PATH="$PATH:/sbin"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

cd $PWD
