#!/usr/bin/env ruby
require 'shellwords'

if ENV['SKIP_JIRA']
  puts "SKIP_JIRA set" if ENV['DEBUG']
  exit 0
end

if File.exist?(".git/MERGE_HEAD")
  puts "Skipping due to merge" if File.exist?(".git/MERGE_HEAD")
  exit 0
end

story=`git story`.strip
project=`git project`.strip

message = File.read(ARGV[0])

message = message
  .gsub(/\A[A-Z]+-\d+ */, '')
  .gsub(/(Project: )?[A-Z]+-\d+ */, '')
  .gsub(/\n*\z/, "\n")

if message.match(/\A(fixup|squash|amend)!/)
  puts "is fixup" if ENV['DEBUG']
  exit 0
end

if message.match(/\Aref/)
  puts "is refactor" if ENV['DEBUG']
  exit 0
end

if story.empty?
  summary = message.lines[0].strip.shellescape
  description = message.lines[2..-1]&.map{|l| '    ' + l }&.join&.strip&.shellescape

  args = ''
  args += %(-o description=#{description}) if description

  story = %x(
  jira create -p #{project}\
  -o summary=#{summary} #{args}\
  --noedit | ruby -ane 'puts $F[1]'
  ).strip

  exit 1 unless $?.success?

  puts %x(
  git story #{story}
  )
end

File.write(ARGV[0], "#{story} #{message}\nProject: #{story}")
