#!/usr/bin/env ruby
require 'shellwords'

if ENV['SKIP_JIRA']
  exit 0
end

story=`git story`.strip

message = File.read(ARGV[0])
  .gsub(/\n+### Jira.*/, "").tap{ |m| puts m }

if story.empty?
  summary = message.lines[0].strip.shellescape
  description = message.lines[2..-1]&.map{|l| '    ' + l }&.join&.strip&.shellescape

  args = ''
  args += %(-o description=#{description}) if description

  puts %x(
  git story "$( \
    jira create -p ES -o summary=#{summary} #{args} --noedit | \
    ruby -ane 'puts $F[1]'
  )"
  )

  story = `git story`.strip
end

tmp = message + "\n### Jira [#{story}](#{ENV["JIRA_STORY_URL"]}#{story})\n"
File.write(ARGV[0], tmp)
