#! /usr/bin/env ruby

commit_file_path = ARGV[0]

subject_line = File.read(commit_file_path).lines.first.gsub(/BP-\d+/,'')

exit 0 if subject_line.split.first.match(/(fixup!|squash!|merge|mob|amend!|reword!)/i)

unless subject_line.size < 70
  puts "subject is too long"
  exit 1
end

allowed_verbs = /(add|cut|fix|ref)/i
unless subject_line.split.first.match allowed_verbs
  puts "Start commits with one of the following: add, cut, fix, ref"
  exit 1
end
