#! /usr/bin/env ruby

require_relative 'find_and_replace'

if ARGV.empty?
  puts <<-HELP

FInd and REplace

usage: fire <find pattern> <replace pattern> <OPT: file pattern>

fire uses ruby's regexp gsub to match and replace. Wrap patterns in strings for
anything more complex than alphanumeric characters. The default file pattern is
"#{FindAndReplaceText.new.file_pattern}".

Examples:

Replace all occurrences of hello with goodbye:

  fire hello goodbye '*'

Replace all occurrences of hello with goodbye that occur in .yml files.

  fire hello goodbye '*.yml'

Replace foo with bar only if it is at start of the line in default files:

  fire '$foo' bar

  HELP
  exit
end

find = Regexp.new(ARGV[0])
replace = ARGV[1].to_s
file = ARGV[2]
FindAndReplaceText.new(find, replace, file).call
