#!/usr/bin/env bash

# Runs all executable hookname-* hooks and exits after,
# if any of them was not successful.
#
# Based on
# http://osdir.com/ml/git/2009-01/msg00308.html

pids=()
#exitcodes=()
hookname=$(basename $0)

if [ $DEBUG ]; then printf "$hookname\n"; fi

# Run each hook, passing through STDIN and storing the exit code.
# We don't want to bail at the first failure, as the user might
# then bypass the hooks without knowing about additional issues.

for hook in $PWD/.git/hooks/$hookname.d/*; do
  if [ $DEBUG ]; then printf "$hook\n"; fi
  test -x "$hook" || continue
  $hook "$@" &
  pids+=($!)
done

for pid in "${pids[@]}"; do
  wait $pid || exit $?
done

wait

# # If any exit code isn't 0, bail.

# for i in "${exitcodes[@]}"; do
  # [ "$i" == 0 ] || exit $i
# done
