#!/usr/bin/env ruby

commit_file_path = ARGV[0]

commit_msg = File.read(commit_file_path)
puts commit_msg if ENV['DEBUG']

comment_char = `git config --get core.commentchar` || "#"
commit_msg_no_cmt = commit_msg.gsub(/^#.*\n/, '')
puts commit_msg_no_cmt if ENV['DEBUG']

commit_msg_unwrapped = commit_msg_no_cmt.gsub(/(\S)\n(\w)/, '\1 \2')
puts commit_msg_unwrapped if ENV['DEBUG']

commit_msg_rewrapped = commit_msg_unwrapped.gsub(/(.{1,72})\s/, "\\1\n").gsub("``` ", "```\n")
puts commit_msg_rewrapped if ENV['DEBUG']

File.write(commit_file_path, commit_msg_rewrapped)
